metalshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

metalshop/metalshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('user/', include('users.urls', namespace='user')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

metalshop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

metalshop/orders/models.py
from django import forms
from django.db import models
from users.models import User
from main.models import Product
from django.conf import settings

class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, default=None)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    city = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=10)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    stripe_id = models.CharField(max_length=250, blank=True)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created'])
        ]

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

    def get_stripe_url(self):
        if not self.stripe_id:
            return ''
        if '_test_' in settings.STRIPE_SECRET_KEY:
            path = '/test/'
        else:
            path = '/'
        return f'https://dashboard.stripe.com{path}payments/{self.stripe_id}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

metalshop/orders/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']
        # опційно: можна визначити віджети
        widgets = {
            'email': forms.EmailInput(attrs={'placeholder': 'Email'}),
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

        # автозаповнення полів для залогіненого користувача
        if self.request.user.is_authenticated:
            self.initial['first_name'] = self.request.user.first_name
            self.initial['last_name'] = self.request.user.last_name
            self.initial['email'] = self.request.user.email

    def save(self, commit=True):
        order = super().save(commit=False)
        order.user = self.request.user
        if commit:
            order.save()
        return order

metalshop/orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import OrderItem, Order
from .forms import OrderCreateForm
from cart.cart import Cart
from django.urls import reverse


# Create your views here.


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST, request=request)
        if form.is_valid():
            order = form.save()
            for item in cart:
                discount_price = item['product'].sell_price()
                OrderItem.objects.create(
                    order=order,
                    product=item['product'],
                    price=discount_price,
                    quantity=item['quantity'],
                )
            cart.clear()
            request.session['order_id'] = order.id
            return redirect(reverse('payment:process'))
    else:
        form = OrderCreateForm(request=request)
    return render(request, 'order/create.html', {'cart': cart, 'form': form})

metalshop/orders/templates/order/create.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}
    Create Order
{% endblock %}

{% block content %}
    <section class="create-order">
        <h2 class="text-center">Create Order</h2>

        {% if form.errors %}
            <div class="alert alert-danger">{{ form.errors }}</div>
        {% endif %}

        <form action=" {% url 'orders:order_create' %}" class="order-form" method="post">
            {% csrf_token %}

            <label for="id_first_name" class="form-label">Name</label>
            <input type="text" name="first_name" required class="form-control form-style" id="id_first_name"
                   placeholder="First Name" value="{{ form.first_name.value|default:'' }}">

            <label for="id_last_name" class="form-label">Last Name</label>
            <input type="text" name="last_name" required class="form-control form-style" id="id_last_name"
                   placeholder="Last Name" value="{{ form.last_name.value|default:'' }}">

            <label for="id_email" class="form-label">Email</label>
            <input type="text" name="email" required class="form-control form-style" id="id_email"
                   placeholder="Email" value="{{ form.email.value|default:'' }}">


            <label for="id_address" class="form-label">Address</label>
            <input type="text" name="address" required class="form-control form-style" id="id_address"
                   placeholder="Address" value="{{ form.address.value|default:'' }}">

            <label for="id_postal_code" class="form-label">Postal Code</label>
            <input type="text" name="postal_code" required class="form-control form-style" id="id_postal_code"
                   placeholder="Postal Code" value="{{ form.postal_code.value|default:'' }}">

            <label for="id_city" class="form-label">City</label>
            <input type="text" name="city" required class="form-control form-style" id="id_city"
                   placeholder="City" value="{{ form.city.value|default:'' }}">


            <input type="submit" value="Place Order" class="button">
        </form>

        <div class="checkout">
            <h2>Checkout</h2>
            <div class="order-info">
                {% for item in cart %}
                    <li>
                        {{ item.quantity }} x {{ item.product.name }}
                        <p>Price: {{ item.total_price }}</p>
                    </li>
                {% endfor %}
                <p>Total: {{ cart.get_total_price }}</p>
            </div>
        </div>
    </section>
{% endblock %}

metalshop/orders/templates/order/created.html
{% extends 'main/base.html' %}

{% block title %}
    Order Created
{% endblock %}

{% block content %}
    <h2 class="text-center">Your order has been placed. Order number - {{ order.id }}</h2>
{% endblock %}