metalshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

metalshop/metalshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('user/', include('users.urls', namespace='user')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

metalshop/payment/urls.py
from django.urls import path
from . import views, webhooks

app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_process, name='process'),
    path('completed/', views.payment_completed, name='completed'),
    path('canceled/', views.payment_canceled, name='canceled'),
    path('webhook/', webhooks.stripe_webhook, name='stripe_webhook'),
    path('test-webhook/', views.test_webhook, name='test_webhook'),
]

metalshop/payment/models.py
from django.db import models

# Create your models here.

metalshop/payment/views.py
from django.shortcuts import render, redirect, get_object_or_404
from decimal import Decimal, ROUND_HALF_UP
from orders.models import Order
from django.conf import settings
import stripe
from django.urls import reverse
import logging
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseRedirect, HttpResponse

# Create your views here.


stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION


def to_cents(d: Decimal) -> int:
    return int((d.quantize(Decimal('0.01'), rounding=ROUND_HALF_UP) * 100).to_integral_value())


def payment_process(request):
    order_id = request.session.get('order_id', None)
    order = get_object_or_404(Order, id=order_id)

    if request.method == 'POST':
        success_url = request.build_absolute_uri(
            reverse('payment:completed')
        )
        cancel_url = request.build_absolute_uri(
            reverse('payment:canceled')
        )
        session_data = {
            'mode': 'payment',
            'client_reference_id': str(order.id),
            'success_url': success_url,
            'cancel_url': cancel_url,
            'line_items': [],
            'payment_intent_data': {
                'metadata': {'order_id': str(order.id)},
            },
        }

        for item in order.items.all():
            discounted_price = item.product.sell_price()
        session_data['line_items'].append({
            'price_data': {
                'unit_amount': int(discounted_price * Decimal('100')),
                'currency': 'usd',
                'product_data': {
                    'name': item.product.name,
                },
            },
            'quantity': item.quantity,
        })
        session = stripe.checkout.Session.create(**session_data)
        logger = logging.getLogger("stripe")
        logger.info("Created session %s for order %s", session.id, order.id)

        return redirect(session.url, code=303)
    else:
        return render(request, 'payment/process.html', locals())


def payment_completed(request):
    return render(request, 'payment/completed.html')


def payment_canceled(request):
    return render(request, 'payment/canceled.html')


@csrf_exempt
def test_webhook(request):
    print("🔥 Test webhook received", request.method)
    return HttpResponse("OK")

metalshop/payment/templates/payment/canceled.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}
    Payment Canceled
{% endblock %}

{% block content %}
    <h2>Payment Canceled</h2>
{% endblock %}

metalshop/payment/templates/payment/competed.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}
    Payment Completed
{% endblock %}

{% block content %}
    <h2>Payment Completed</h2>
{% endblock %}

metalshop/payment/templates/payment/completed.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}
    Payment Completed
{% endblock %}

{% block content %}
    <h2>Payment Completed</h2>
{% endblock %}

metalshop/payment/templates/payment/process.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}
    Payment Process
{% endblock %}

{% block content %}
    <div class="payment">
        <h2 class="text-center">Payment</h2>

        <div class="order">
            {% for item in order.items.all %}
                {% with product=item.product %}
                    <div class="order__item d-flex gap-4 align-items-center justify-content-between">
                        <div class="order__item__left d-flex align-items-center gap-4">
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image.url %} {{ product.image.url }}{% else %}{% static 'img/noimage.png' %}{% endif %}"
                                     alt="">
                            </a>
                            <div class="order__item-info">
                                <h4 class="mb-0">{{ product.name }}</h4>
                            </div>
                        </div>
                        <div class="order__item__right d-flex align-items-center gap-4">
                            <div class="order__item-item-q">
                                <p class="mb-0">Quantity: {{ item.quantity }}</p>
                            </div>
                            <div class="order__item-item-controls">
                                <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                                    <input type="submit" class="button remove-btn button-red" value="remove">
                                    {% csrf_token %}
                                </form>
                            </div>
                            <div class="order__item-item-price">
                                {% if product.discount %}
                                    <div class="discount d-flex gap-4 align-items-center">
                                        <p class="through mb-0">{{ product.price }}</p>
                                        <p class="price mb-0">{{ product.sell_price }}</p>
                                    </div>
                                {% else %}
                                    <p class="price mb-0">{{ product.price }}</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endwith %}
            {% endfor %}

            <div class="total pt-4 text-end">
                <h4>Total Sum: {{ order.get_total_cost }}</h4>
            </div>


            <form action="{% url 'payment:process' %}" method="post"
                  class="payform mt-4 text-center justify-content-center">
                <input type="submit" name="" id="" value="Pay now" class="paynow button button-black">
                {% csrf_token %}
            </form>
        </div>


    </div>
{% endblock %}