metalshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

metalshop/main/urls.py
from django.urls import include, path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.popular_list, name='popular_list', ),
    path('shop/', views.products_list, name='products_list'),
    path('shop/<slug:slug>/', views.product_detail, name='product_detail'),
    path('shop/category/<slug:cat_slug>/', views.products_list, name='products_list_by_cat'),
]

metalshop/metalshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('user/', include('users.urls', namespace='user')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

metalshop/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile')
]

metalshop/main/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(max_length=30, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:products_list_by_cat', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.PROTECT)

    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=6)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    discount = models.DecimalField(default=0.00, max_digits=4, decimal_places=2)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created'])
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:product_detail', args=[self.slug])

    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2)
        return self.price


class ProductImage(models.Model):
    product = models.ForeignKey(Product, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    def __str__(self):
        return f'{self.product.name} - {self.image.name}'

metalshop/main/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.core.paginator import Paginator
from cart.forms import CartAddProductForm


# Create your views here.

def popular_list(request):
    products = Product.objects.filter(available=True)[:3]
    return render(request, 'main/index/index.html', {'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, available=True)
    cart_product_form = CartAddProductForm
    return render(request, 'main/product/detail.html', {'product': product, 'cart_product_form': cart_product_form})


def products_list(request, cat_slug=None):
    cat = None
    cats = Category.objects.all()
    products = Product.objects.filter(available=True)

    page = request.GET.get('page', 1)
    paginator = Paginator(products, 3)
    current_page = paginator.page(int(page))

    if cat_slug:
        cat = get_object_or_404(Category, slug=cat_slug)
        products = products.filter(category=cat)
        paginator = Paginator(products.filter(category=cat), 3)
        current_page = paginator.page(int(page))
    return render(request, 'main/product/shop.html',
                  {'category': cat, 'categories': cats, 'products': current_page, 'cat_slug': cat_slug})

metalshop/main/templates/main/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> {% block title %}{% endblock %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alegreya:ital,wght@0,400..900;1,400..900&family=Bodoni+Moda+SC:ital,opsz,wght@0,6..96,400..900;1,6..96,400..900&display=swap"
          rel="stylesheet">

    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
<header class="header sticky-top">
    <div class="header__container d-flex">
        <nav class="header__nav">
            <ul class="header__menu d-flex">
                <li><a href="/" class="header__menu-link m-3">Home</a></li>
                <li><a href="/shop" class="header__menu-link m-3">Shop</a></li>
            </ul>
        </nav>
        <div class="header__logo">
            <a href="/"> <img src=" {% static 'img/logo.png' %}" alt=""> </a>
        </div>

        <div class="header__profile d-flex align-items-center justify-content-center gap-4">
            <div class="header__cart">
                <a href="{% url 'cart:cart_detail' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                        <path d="M351.9 329.506H206.81l-3.072-12.56H368.16l26.63-116.019-217.23-26.04-9.952-58.09h-50.4v21.946h31.894l35.233 191.246a32.927 32.927 0 1 0 36.363 21.462h100.244a32.825 32.825 0 1 0 30.957-21.945zM181.427 197.45l186.51 22.358-17.258 75.195H198.917z"
                              data-name="Shopping Cart"/>
                    </svg>
                </a>
                <p class="header__cart-q">
                    {% with cart_quantity=cart|length %}
                        {% if cart_quantity > 0 %}
                            {{ cart_quantity }}
                        {% else %}
                            0
                        {% endif %}
                    {% endwith %}
                </p>
            </div>
            <div class="header__user d-flex align-items-center gap-4">
                {% if user.is_authenticated %}
                    <p class="user-name">Hello, <a href="{% url 'user:profile' %}">{{ user.username }}</a>!</p>
                    <a href="{% url 'user:logout' %}">Logout</a>
                {% else %}
                    <a href="{% url 'user:login' %}">Login</a>
                    <a href="{% url 'user:registration' %}">Register</a>
                {% endif %}
            </div>

        </div>
    </div>
</header>

<div class="main">
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
</div>


<script src="{% static  'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>