metalshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

metalshop/main/urls.py
from django.urls import include, path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.popular_list, name='popular_list', ),
    path('shop/', views.products_list, name='products_list'),
    path('shop/<slug:slug>/', views.product_detail, name='product_detail'),
    path('shop/category/<slug:cat_slug>/', views.products_list, name='products_list_by_cat'),
]

metalshop/metalshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('user/', include('users.urls', namespace='user')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

metalshop/main/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(max_length=30, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:products_list_by_cat', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.PROTECT)

    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=6)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    discount = models.DecimalField(default=0.00, max_digits=4, decimal_places=2)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created'])
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:product_detail', args=[self.slug])

    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2)
        return self.price


class ProductImage(models.Model):
    product = models.ForeignKey(Product, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    def __str__(self):
        return f'{self.product.name} - {self.image.name}'

metalshop/main/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.core.paginator import Paginator
from cart.forms import CartAddProductForm


# Create your views here.

def popular_list(request):
    products = Product.objects.filter(available=True)[:3]
    return render(request, 'main/index/index.html', {'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, available=True)
    cart_product_form = CartAddProductForm
    return render(request, 'main/product/detail.html', {'product': product, 'cart_product_form': cart_product_form})


def products_list(request, cat_slug=None):
    cat = None
    cats = Category.objects.all()
    products = Product.objects.filter(available=True)

    page = request.GET.get('page', 1)
    paginator = Paginator(products, 3)
    current_page = paginator.page(int(page))

    if cat_slug:
        cat = get_object_or_404(Category, slug=cat_slug)
        products = products.filter(category=cat)
        paginator = Paginator(products.filter(category=cat), 3)
        current_page = paginator.page(int(page))
    return render(request, 'main/product/shop.html',
                  {'category': cat, 'categories': cats, 'products': current_page, 'cat_slug': cat_slug})

metalshop/main/templates/main/product/detail.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
    <section class="product d-flex gap-4 pt-4">

        <div class="product__images">
            {% if product.images.all|length > 1 %}
                {% for image in product.images.all %}
                    <img class="product__images-item" src="{{ image.image.url }}" alt="" style="display: none"
                         data-index="{{ forloop.counter0 }}">
                {% endfor %}
            {% else %}
                <img class="product__images-item" src="{{ product.image.url }}" alt="">
            {% endif %}

            <div class="product__image-nav">
                <button class="prev-bnt">&lsaquo;</button>
                <button class="next-bnt">&rsaquo;</button>
            </div>
            <script>
                const images = document.querySelectorAll('.product__images-item');
                const prev_btn = document.querySelector('.prev-bnt');
                const next_btn = document.querySelector('.next-bnt');
                let currentIndex = 0;
                images[currentIndex].style.display = 'block';
                if (images.length === 1) {
                    prev_btn.style.display = 'none'
                    next_btn.style.display = 'none'
                } else {
                    prev_btn.addEventListener('click', () => {
                        images[currentIndex].style.display = 'none';
                        currentIndex = (currentIndex - 1 + images.length) % images.length;
                        images[currentIndex].style.display = 'block'
                    })
                    next_btn.addEventListener('click', () => {
                        images[currentIndex].style.display = 'none';
                        currentIndex = (currentIndex + 1) % images.length;
                        images[currentIndex].style.display = 'block'
                    })
                }
            </script>

        </div>
        <div class="product__info">
            <h2>{{ product.name }}</h2>
            <h3>{{ product.category }}</h3>
            <p>{{ product.description |linebreaks }}</p>
            {% if product.discount %}
                <div class="discount d-flex gap-4 align-items-center">
                    <p class="through">{{ product.price }}</p>
                    <p class="price">{{ product.sell_price }}</p>
                </div>
            {% else %}
                <p class="price">{{ product.price }}</p>
            {% endif %}

            <form action="{% url 'cart:cart_add' product.id %}" method="post" class="product__add-to-cart">
                {{ cart_product_form }}
                {% csrf_token %}
                <input type="submit" class="add-to-cart-btn btn button mt-4" value="Add to Cart">
            </form>
        </div>
    </section>
{% endblock %}

metalshop/main/templates/main/product/shop.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
    SHOP
{% endblock %}

{% block content %}
    <div class="shop">
        <div class="topbar d-flex align-items-center">
            <h4 class="mb-0">Categories:</h4>
            <ul class="d-flex align-items-center gap-4 p-4">
                <li {% if not category %} class="selected" {% endif %}>
                    <a href="{% url 'main:products_list' %}"> ALL </a>
                </li>
                {% for category in categories %}
                    <li {% if category.slug == cat_slug %} class="selected" {% endif %}>
                        <a href="{{ category.get_absolute_url }}"> {{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>

        <div class="products-list d-flex gap-4">
            {% for product in products %}
                <div class="products-list__item">
                    <a href="{{ product.get_absolute_url }}" class="home__recs-card  d-flex flex-column">
                        <img src="{% if product.image %} 
                            {{ product.image.url }}{% else %} {% static 'img/noimage.png' %} {% endif %}" alt="">
                        <h4> {{ product.name }}</h4>
                        {% if product.discount %}
                            <div class="discount d-flex gap-4 align-items-center">
                                <p class="through">{{ product.price }}</p>
                                <p class="price">{{ product.sell_price }}</p>
                            </div>
                        {% else %}
                            <p class="price">{{ product.price }}</p>
                        {% endif %}
                    </a>
                </div>
            {% endfor %}
        </div>


        <div class="pagination d-flex align-items-center justify-content-center">
            <ul class="d-flex gap-2">
                <li class=" {% if not products.has_previous %} disabled {% endif %}">
                    <a href="{% if products.has_previous %}?page={{ products.previous_page_number }}{% endif %}">Previous</a>
                </li>
                {% for page in products.paginator.page_range %}
                    {% if page >= products.number|add:-2 and page <= products.number|add:2 %}
                        <li>
                            <a href="?page={{ page }}"
                               class="{% if products.number == page %}disabled {% endif %}">{{ page }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
                <li class=" {% if not products.has_next %} disabled {% endif %}">
                    <a href="{% if products.has_next %}?page={{ products.next_page_number }}{% endif %}">Next</a>
                </li>
            </ul>
        </div>

    </div>
{% endblock %}